root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main"
bin = "tmp/bin"

# 80番ポートで起動するように実行時引数を指定
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

incliude_ext = ["go", "tpl", "tmpl", "html"]
excliude_ext = ["assets", "tmp", "vendor"]
include_dir = []
exclude_dir = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true