linters-settings:
  goimports:
    local-prefixes: github.com/stwile/go_todo_app
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  linters:
    disable-all: true
    enable:
      - gocyclo
      - gofmt
      - goimports
      - govet
      - ineffassign
      - lll